USE [master]
GO

/****** Object:  Database [EmployeeSurveyDB]    Script Date: 9/3/2025 9:14:47 AM ******/
CREATE DATABASE [EmployeeSurveyDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeeSurveyDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EmployeeSurveyDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmployeeSurveyDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EmployeeSurveyDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeeSurveyDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmployeeSurveyDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmployeeSurveyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmployeeSurveyDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EmployeeSurveyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmployeeSurveyDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET RECOVERY FULL 
GO

ALTER DATABASE [EmployeeSurveyDB] SET  MULTI_USER 
GO

ALTER DATABASE [EmployeeSurveyDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmployeeSurveyDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmployeeSurveyDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmployeeSurveyDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EmployeeSurveyDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmployeeSurveyDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EmployeeSurveyDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [EmployeeSurveyDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [EmployeeSurveyDB] SET  READ_WRITE 
GO

